### ISSUE TITLE
Choice of challenge format

### ISSUE THREAD

**Issue by joezuntz** [TallJimbo/great4-general#2]
There are number of ways that any challenge associated with Great4 could be structured, if we need one at all.  The purpose of this issue is to consider possible formats for a Great4 challenge and get the opinion of the different survey teams on them.
## Purpose of challenges

In general the WL challenges may have these motivations:
- **Bring people into the community.** Earlier challenges focused on bringing new people from other communities into the WL fold.  This was an excellent achievement of earlier challenges, but given the increased maturity of the field is no longer a strong motivator.  We should be wary of a selection bias here though - we cannot assume all potentially interested people are already involved.
- **Motivate people to work hard on shape measurement** The challenges provided a strong motivator for many people, from old hands to new blood, to work intensely on shape measurement. The friendly competition they inspired triggered bursts of shape measurement work, methods, and papers. Given the pressing needs of the surveys already providing strong motivators this is also less of an issue now.
- **Provide agreed-upon testbed data sets.** The legacy value of the GREAT challenges has been significant - new groups can be quickly pointed to the datasets from the challenges as a good place to start working, and new algorithms have an excellent first hurdle to get over before being seriously considered by the community.
- **Explore specific aspects of the problem.** Another truly vital part of the Great challenges has been to pull apart the shape measurement problem into specific parts - like noise level, bulge vs disc, real vs simulated, multi-exposure vs single, etc,  and show how shape measurement in general and individual methods react to them. This has been invaluable in clarifying the problems we face. We identified blending as the next such issue.
- **Rank individual approaches.** The previous surveys have been powerful pointers that have shown the field which general methods and indeed individual codes are worthy of further exploration and attention.
- **Test individual teams.** Because of the subtle dependence of many methods on the details of their usage, the challenges also provide a way to prove that specific teams have the ability to work on real data. This is something of a double-edged sword since Great4 work would require time taken away from real survey prep and analysis.
- **Demonstrate to the wider cosmology community that we are ready for surveys.** The previous challenges have sent an important message to the wider cosmology world that we are actively testing each other to prove that we are ready to work on real data (or not ready, in the case of the early surveys that flagged problems). This proof was significantly more powerful than any internal testing could possibly be.
- **Demonstrate to the funding agencies that we are ready for surveys.**  Agency stakeholders, being somewhat removed from the field, and having a more checklist-like approach to survey readiness, are much more likely to be persuaded by internal testing than the wider community would be. But they might still find independent testing to be of value.
## Downsides of challenges
- **Time.** The primary downside of the challenges is the time they take, both for the organizer and participants. The amount of time taken is very large indeed and the return on investment of any challenge should be carefully considered.
- **Potentially misleading results** If challenges are not tailored carefully enough to the specific needs of a survey then any results based on it could give misleading results about the methods used for it.
- **Excessive competetiveness.** Previous challenges have been mostly friendly, but intense competition can inspire intense rivalry and damage collegiality.
- **Scaring stakeholders.** If a survey team does not achieve good enough challenge results this can spook funding agencies.  If the challenge were a good enough reflection of the real data this might be a justified spooking, but if the results are misleading (see above) then it would be a problem.  This worry was expressed by one of the survey teams at the meeting.
## Possible Formats

**1. No Challenge.** Given the noted downsides and the coalescing of the community into the survey teams, the software tasks proposed at the Penn meeting may be sufficient to be useful without any associated challenge. The surveys could then use it internally or publically as they wish.

**2. Full Great-style challenge.** The successes of the previous challenges might motivate us to consider a full challenge, with leaderboards, deadlines, and prizes. This might be the best way of pushing people to explore the deblending issue.

**3. Leaderboard but no time limits.** We could have a Great-style leader board but without any time limit or prize. Teams wishing to evaluate their work could test their score on a leader board. Team results could be made private until the team wishes to publicly share their results. To avoid a publication bias, a team would be able to make all their results public or none of them, but not just their favored results.

**4. External challenger team.** One option that tries to deal with the "misleading results" problem is for (disinterested parts of) the Great4 executive to act as an external challenger to produce simulations for surveys that ask to be challenged.  Based on agreed-on survey configurations and free parameters, the G4 team would generate simulations for any team that requests it, and on receipt of measured results provide a Q factor. This would enable teams that would like to have blind external challenges to have them, and specifically tailored to their project. We would need to gauge interest in this from the surveys and teams, and ensure that an agreed-on survey configuration is "official" in some way.

**5. External challenger team (extended).** The external challenger team concept could be extended in a number of directions: 
- We should have branches within the survey-specific results.
- The data sets could be made public, so that other teams who would like to prove that they can also analyze data from a particular survey can do so. 
- We could have a leaderboard so that other teams can participate publicly.
- We could also consider a publication policy, stating that some result will be published in some way by some date, even if it is bad, to add accountability.

Comments on all these proposals, or thoughts on alternative or hybrid proposals, are now solicited.

**Comment by rmandelb** [comment]
GitHub has done something amusing with your numbering (options 1, 2, 3, 3, 4).  Edited: never mind, you fixed it!

Anyway, a comment on number 3: you could imagine a variant that has a soft deadline for inclusion in some initial community-written results paper.  Deadlines are artificial but sometimes they are a useful forcing function.  And for those who want more time, they can continue to work on it after that and include results in their own paper?

Comment on numbers 4 and 5: I worry that this could generate a potentially infinite amount of work for the GREAT4 team members.  I mean, there aren't infinitely many surveys, but if even 3 take you up on the offer, and have sufficiently arcane/complex requirements to ensure that a configuration is "official", that could be tons of work.  In contrast, option 1 encourages them to do this themselves and make the relevant scripts available at least internally, but ideally publicly, which seems like it's doing a better job of optimizing cost vs. benefit.

**Comment by joezuntz** [comment]
Thanks - I've modified this now so your comments now refer to number 3 (your paragraph two) and  numbers 4 and 5 (your paragraph three).

**Comment by rmandelb** [comment]
Ah thanks, I went ahead and edited mine as well.

**Comment by joezuntz** [comment]
Also good point on the note about work time - I think we'd have to carefully structure who did what work for it to be possible at all. Maybe if the galsim simulation config code is flexible enough that could be left to the survey teams?

Also, one quick meta-note - just because there are two more "extreme" options (1, 2) doesn't mean I favour the ones in the middle (3, 4, 5)!  I think there are strong arguments for all the options there.

**Comment by msimet** [comment]
A possible way to reduce the amount of work in 4 and 5 is to have a small (perhaps rotating) advisory committee, and then ask the survey in question to nominate someone to work with that committee to make the actual simulations.  They'd have to agree to various conditions such as keeping the parameters blinded for the rest of their survey team.  I think we have interested representatives from most of the large surveys already, don't we?

This would also potentially solve the data transfer problem, as the survey-specific person could create the simulations on whichever computer would be used to analyze them.

**Comment by joezuntz** [comment]
It's been nearly a year since we opened this issue, and based on discussions I've had with people from the various surveys it seems like there isn't an appetite at this time for a further challenge - no one has the time, and given the very different requirements for the different upcoming surveys it seems like option 1, "no challenge" is the favoured one.

I'd suggest we revisit this in a year or so or the next time we have a shape measurement meeting, but for now I will close this issue.
